### ISSUE TITLE
Bairoil, WY

### ISSUE THREAD

**Issue by ItoErika** [UW-Macrostrat/burwell-processing#196]
## Info
**Name:**
Geologic Map Of The Bairoil 30' X 60' Quadrangle, Carbon, Sweetwater, Fremont, And Natrona Counties, Wyoming

**Source URL:**
GIS Data: http://www.wsgs.wyo.gov/gis-files/mapseries/100k/bedrock/gis-2011-ms-86.zip
PDF: http://www.wsgs.wyo.gov/products/wsgs-2011-ms-86.pdf

**Estimated scale:**
large

**Number of bedrock polygons:**

**Lithology field:**
name
**Time field:**
age,early_id,late_id
**Stratigraphy name field:**
strat_name,hierarchy
**Description field:**
description
**Comments field:**
comments
**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Match
- [ ] Roll tiles

**Comment by cambro** [comment]
I removed the 4 records from maps.large that were causing this (they were line strings and it's not clear why/what they were in the original data).
https://dev.macrostrat.org/burwell/#10/42.2499/-107.5012
