### ISSUE TITLE
Bolivia

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#269]
**Name:**
Mapa geológico de Bolivia, 2000

**Source URL:**
https://geo.gob.bo/geonetwork/srv/eng/catalog.search#/metadata/9d4640bf-522a-4949-9a14-4838685c5a2c

**Estimated scale:**
small?

**Folder name:**
`bolivia`

**Dataset names:**

**Number of bedrock polygons:**

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

**Comments field:**

**Comments:**

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by cambro** [comment]
This seems like it has no data associated with besides the geometries
