### ISSUE TITLE
Ogdon, UT

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#287]
**Name:**
Interim geologic map of the Ogden 30′ x 60′ quadrangle, Box Elder, Cache, Davis, Morgan, Rich, and Summit Counties, Utah, and Uinta County, Wyoming

**Source URL:**
GIS Data: http://ugspub.nr.utah.gov/publications/GIS_maps/Ogden3060_ofr-653.zip
PDF: https://ugspub.nr.utah.gov/publications/open_file_reports/ofr-653.pdf
Index page: http://geology.utah.gov/map-pub/maps/gis/#tab-id-1

**Estimated scale:**
large

**Folder name:**
ut_ogden

**Dataset names:**

**Number of bedrock polygons:**

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

**Comments field:**

**Comments:**

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,lith,descrip,strat_name,t_interval,b_interval,comments,geom) 
SELECT gid,262,unitname,age_strat,compositio,descrip,strat_name,late_id,early_id,genesis,ST_MakeValid(geom) FROM sources.ut_ogden where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid,262,feature,featurenam,new_type,ST_MakeValid(geom) FROM sources.ut_ogden_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,262,strike,dipangle,dipdirecti,point_type,feature,ST_MakeValid(geom) FROM sources.ut_ogden_points where point_type is not null and geom is not null;
```
Also note that the strike, dipangle, and dipdirecti values for some of the points seem incorrect.

**Comment by cambro** [comment]
source_id 262
https://dev.macrostrat.org/burwell#10/41.249945/-111.500755
