### ISSUE TITLE
Salt Lake City, UT

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#288]
**Name:**
Geologic map of the Salt Lake City 30′ x 60′ quadrangle, north-cental Utah, and Uinta County, Wyoming

**Source URL:**
GIS Data: http://ugspub.nr.utah.gov/publications/GIS_maps/SaltLakeCity3060.zip
PDF: https://ugspub.nr.utah.gov/publications/geologicmaps/30x60quadrangles/m-190.pdf
Index page: http://geology.utah.gov/map-pub/maps/gis/#tab-id-1

**Estimated scale:**
large

**Folder name:**

**Dataset names:**

**Number of bedrock polygons:**

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
source_id 251
This one required extensive copying and pasting descriptions and harmonizing time intervals.
