### ISSUE TITLE
Myersville & Smithsburg, MD

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#307]
**Name:**
Geologic Map of the Myersville Quadrangle and Maryland portion of the Smithsburg Quadrangle, Washington and Frederick Counties, Maryland

**Source URL:**
PDF: http://www.mgs.md.gov/output/maps/quadgeo/MY_SMGEO2009_1.pdf
GIS: http://www.mgs.md.gov/output/maps/quadgeo/GISdata/MY_SM_2009_1.zip
Index: http://www.mgs.md.gov/publications/data_pages/quadrangle_geo.html

**Estimated scale:**
large

**Folder name:**

**Dataset names:**

no points file (points shapefiles are ornaments)
**Number of bedrock polygons:**

**Lithology field:**
unit_name, lith_abbre

**Time field:**
age,early_id,late_id

**Stratigraphy name field:**

strat_name, hierarchy

**Description field:**
description

**Comments field:**

comments

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
this source appears to have overlapping polygons (i..e, quaternary not separated from bedrock)

**Comment by cambro** [comment]
Bedrock map contained 9 polygons with no data (besides geometry). These needed to be filled in manually. by reference to original map.

**Comment by cambro** [comment]
fix involved deleting polygons were null data values for all except geometry. quaternary separated into separate md_myerssmith_q table
