### ISSUE TITLE
Clear Spring and Hedgesville, MD

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#310]
**Name:**
Geologic and Karst Features Map of the Maryland Portions of the Clear Spring and Hedgesville Quadrangles, Washington County, Maryland

**Source URL:**
PDF: http://www.mgs.md.gov/output/maps/quadgeo/CL_HE2014.pdf
GIS: http://www.mgs.md.gov/output/maps/quadgeo/GISdata/CL_HE_2014_1.zip
Index: http://www.mgs.md.gov/publications/data_pages/quadrangle_geo.html

**Estimated scale:**
large

**Folder name:**

**Dataset names:**

**Number of bedrock polygons:**

**Lithology field:**

name, 
**Time field:**

age,early_id,late_id

**Stratigraphy name field:**
strat_name,hierarchy

**Description field:**

description
**Comments field:**

**Comments:**
comments

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
this one overlaps with md_western and seems to also have a complicated Quaternary geology (i.e., polygons overlap)
