### ISSUE TITLE
Keedysville, MD

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#312]
**Name:**
Geologic Map of Keedysville and parts of Shepherdstown, Harpers Ferry and Charles Town Quadrangles, Washington and Frederick Counties, Maryland

**Source URL:**
PDF: http://www.mgs.md.gov/output/maps/quadgeo/K_SHCGEO_2009_1.pdf
GIS: http://www.mgs.md.gov/output/maps/quadgeo/GISdata/K_SHC_2009_1.zip
Index: http://www.mgs.md.gov/publications/data_pages/quadrangle_geo.html

**Estimated scale:**
large

**Folder name:**

**Dataset names:**

**Number of bedrock polygons:**

**Lithology field:**

unit_name
**Time field:**

age,early_id,late_id

**Stratigraphy name field:**

strat_name,hierarchy

**Description field:**

description
**Comments field:**
comments

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
this one required quite a bit of clean up. A bunch of polygons had null data but appeared to be duplicates of those with data. Quaternary needed to be offloaded into md_keedysvill_q

**Comment by cambro** [comment]
source_id 222
https://dev.macrostrat.org/burwell/#12/39.4268/-77.7104
