### ISSUE TITLE
Catoctin Furnace, MD

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#318]
**Name:**
Catoctin Furnace, MD

**Source URL:**
PDF: http://www.mgs.md.gov/output/maps/quadgeo/CATOCGEO2004_1.pdf
GIS: http://www.mgs.md.gov/output/maps/quadgeo/GISdata/CATOC_2004_1.zip
Index: http://www.mgs.md.gov/publications/data_pages/quadrangle_geo.html

**Estimated scale:**
large

**Folder name:**

**Dataset names:**

**Number of bedrock polygons:**

**Lithology field:**
 name

**Time field:**
 age, early_id,late_id

**Stratigraphy name field:**

strat_name

**Description field:**
 description

**Comments field:**
comments

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
source_id 232
https://dev.macrostrat.org/burwell#10/39.5626/-77.437205

**Comment by cambro** [comment]
needed extensive cleaning. a bunch of geometries with null values removed. quaternary geology moved to separate table, not processed/rolled (md_catocinfurnace_q)
