### ISSUE TITLE
New Windsor, MD

### ISSUE THREAD

**Issue by jczaplew** [UW-Macrostrat/burwell-processing#321]
**Name:**
New Windsor, MD

**Source URL:**
PDF: http://www.mgs.md.gov/output/maps/quadgeo/NEWWIGEO2004_1.pdf
GIS: http://www.mgs.md.gov/output/maps/quadgeo/GISdata/NEWWI_2004_1.zip
Index: http://www.mgs.md.gov/publications/data_pages/quadrangle_geo.html

**Estimated scale:**
large

**Folder name:**

**Dataset names:**

**Number of bedrock polygons:**

**Lithology field:**

name, lith_abbre
**Time field:**

age,early_id, late_id

**Stratigraphy name field:**

strat_name,hierarchy

**Description field:**
description

**Comments field:**

comments

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
source_id 220
https://dev.macrostrat.org/burwell#10/39.5626/-77.062205
