### ISSUE TITLE
Cross Roads, AZ

### ISSUE THREAD

**Issue by jmeisburger** [UW-Macrostrat/burwell-processing#330]
**Name:**
Geologic map of the Cross Roads 7.5' Quadrangle and the southern part of the Gene Wash 7.5' Quadrangle, La Paz County, Arizona, and San Bernardino County, California

**Source URL:**
PDF: http://repository.azgs.az.gov/sites/default/files/dlio/files/nid1660/cross_roads_dgm-111_layout_v1.pdf
GDB: http://repository.azgs.az.gov/sites/default/files/dlio/files/nid1660/crossroads.gdb_.zip
Link: http://repository.azgs.az.gov/uri_gin/azgs/dlio/1660

**Estimated scale:**
Large

**Folder name:**

**Dataset names:**

**Number of bedrock polygons:**

**Lithology field:**
Layer: MapUnitPolys

**Time field:**
Layer: DescriptionOfMapUnits
Field: Age

**Stratigraphy name field:**
Layer: MapUnitPolys
Field: MapUnit

**Description field:**
Layer: DescriptionOfMapUnits

**Comments field:**
Layer: Notes

**Comments:**

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by aazaff** [comment]
This map seems to be a bad candidate. I am going to take this off the queue.
