### ISSUE TITLE
Carcajou Canyon, NWT

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#333]
**Name:**
Fallas, K.M. and MacNaughton, R.B., 2014. Geology, Carcajou Canyon (northwest), Northwest Territories; Geological Survey of Canada, Canadian Geoscience Map 94, scale 1:100 000. doi:10.4095/292286

**Source URL:**
https://doi.org/10.4095/292286

**Estimated scale:**
large

**Folder name:**
nwt_carcajou

**Dataset names:**
nwt_carcajou
nwt_carcajou_lines
nwt_carcajou_points

**Number of bedrock polygons:**
270

**Lithology field:**
lith_list

**Time field:**
max_age
min_age

**Stratigraphy name field:**

**Description field:**

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,lith,descrip,comments,strat_name,t_interval,b_interval,geom) 
SELECT gid,255,map_unit,use_age,lith_list,descrip,genesis,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nwt_carcajou where geom is not null;
```

```
INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid,255,name,concat_ws('; ',subfeature,concat('location ',confidence,remarks),concat('age ',concat(max_age,'- ',min_age))),new_type,ST_MakeValid(geom) FROM sources.nwt_carcajou_lines where new_type is not null and geom is not null;
```
points unclear

**Comment by cvavrus** [comment]
Drift map units in a separate .shp file

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,255,strike,dip,dip_dir,point_type,concat_ws('; ',subfeature,remarks),ST_MakeValid(geom) FROM sources.nwt_carcajou_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 255
https://dev.macrostrat.org/burwell#10/64.75/-127.5
