### ISSUE TITLE
Red Fern Lake, BC

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#359]
**Name:**
Lane, L.S., 2004: A GIS dataset of geological features for the Redfern 
Lake map area (94G/5), British Columbia; Geological Survey of Canada, Open File 4603.

**Source URL:**
https://doi.org/10.4095/215465

**Estimated scale:**
large

**Folder name:**
bc_redfern

**Dataset names:**
bc_redfern
bc_redfern_lines
bc_redfern_points

**Number of bedrock polygons:**
193

**Lithology field:**

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
gen_descr

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,formation,use_age,gen_descr,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.bc_redfern where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,1,descrip,new_type,ST_MakeValid(geom) FROM sources.bc_redfern_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,strike,dip,dip_dir,point_type,concat_ws('; ',concat('lithology ',lithology),comment),ST_MakeValid(geom) FROM sources.bc_redfern_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 216

**Comment by cambro** [comment]
```macrostrat process map_source 216```
throws an error. 
```[i] Mismatched .dbf and .shp record count -- possible data loss.
[dissolve] Dissolved 0 features into 0 features
[o] Wrote large216_rgeom.shp
[o] Wrote large216_rgeom.shx
[o] Wrote large216_rgeom.dbf
[o] Wrote large216_rgeom.prj
Shapefile type: Polygon
Postgis type: MULTIPOLYGON[2]
     Validating geometry...
Traceback (most recent call last):
  File "/usr/local/bin/macrostrat", line 11, in <module>
    load_entry_point('macrostrat-cli', 'console_scripts', 'macrostrat')()
  File "/data/projects/macrostrat-cli/cli/cli.py", line 90, in main
    script.run()
  File "/data/projects/macrostrat-cli/cli/commands/process.py", line 61, in run
    script.run(self.args[2:])
  File "/data/projects/macrostrat-cli/cli/commands/process_scripts/map_source.py", line 65, in run
    rgeom.run((source_id, ))
  File "/data/projects/macrostrat-cli/cli/commands/process_scripts/rgeom.py", line 99, in run
    if '--simple' in self.args[0]:
IndexError: tuple index out of range```

**Comment by cambro** [comment]
@jczaplew if you get a sec can you take a quick look at this. this is new behavior, two different maps have failed so something seems to have changed and I'm not sure what.

**Comment by cambro** [comment]
This error is a wrapper script error confined to map_source.py. All of the scripts called by this wrapper work fine.

**Comment by cambro** [comment]
https://dev.macrostrat.org/burwell/#11/57.3747/-123.7315
