### ISSUE TITLE
Mount Prudence, BC

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#364]
**Name:**
McMechan, M.E., 2013. Geology, Mount Prudence, British Columbia; Geological Survey
of Canada, Canadian Geoscience Map 169 (preliminary), scale 1:50 000.
doi:10.4095/293093

**Source URL:**
https://doi.org/10.4095/293093

**Estimated scale:**
large

**Folder name:**
bc_prudence

**Dataset names:**
bc_prudence
bc_prudence_lines
bc_prudence_points

**Number of bedrock polygons:**
69

**Lithology field:**
lith_list

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**
Drift map units in separate .shp file

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,lith,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,use_age,lith_list,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.bc_prudence where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid,1,name,concat_ws('; ',descrip,concat('location ',confidence)),new_type,ST_MakeValid(geom) FROM sources.bc_prudence_lines where new_type is not null and geom is not null;
```
points unclear

**Comment by cvavrus** [comment]
Suggested insert:
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,233,strike,dip,dip_dir,point_type,concat_ws('; ',young_evid,subfeature,method,remarks),ST_MakeValid(geom) FROM sources.bc_prudence_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 233
https://dev.macrostrat.org/burwell#10/59.375/-125.75
