### ISSUE TITLE
Grayling River, BC

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#365]
**Name:**
McMechan, M.E., 2013. Geology, Grayling River, British Columbia; Geological Survey of Canada, Canadian Geoscience Map 115 (preliminary), scale 1:50 000. doi:10.4095/293156

**Source URL:**
https://doi.org/10.4095/293156

**Estimated scale:**
large

**Folder name:**
bc_grayling

**Dataset names:**
bc_grayling
bc_grayling_lines
bc_grayling_points

**Number of bedrock polygons:**
35

**Lithology field:**
lith_list

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**
Drift map units in separate .shp file

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,lith,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,use_age,lith_list,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.bc_grayling where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid,1,name,concat_ws('; ',descrip,concat('location ',confidence)),new_type,ST_MakeValid(geom) FROM sources.bc_grayling_lines where new_type is not null and geom is not null;
```
points unclear

**Comment by cvavrus** [comment]
Suggested insert:
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,strike,dip,dip_dir,point_type,subfeature,ST_MakeValid(geom) FROM sources.bc_grayling_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 239
https://dev.macrostrat.org/burwell#10/59.375/-125.25
