### ISSUE TITLE
Stimson Creek, AB

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#378]
**Name:**
McMechan, M.E., 2013. Geology, Stimson Creek, Alberta; Geological Survey of Canada, Canadian Geoscience Map 24, scale 1:50 000. doi:10.4095/293115

**Source URL:**
https://doi.org/10.4095/293115

**Estimated scale:**
large

**Folder name:**
ab_stimson

**Dataset names:**
ab_stimson
ab_stimson_lines
ab_stimson_points

**Number of bedrock polygons:**
433

**Lithology field:**
lith_list

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**
Drift map units and fault zones located in separate .shp files

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,lith,descrip,comments,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,use_age,lith_list,descrip,genesis,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.ab_stimson where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid,1,name,concat_ws('; ',descrip,concat('location ',confidence)),new_type,ST_MakeValid(geom) FROM sources.ab_stimson_lines where new_type is not null and geom is not null;
```
points unclear

**Comment by cambro** [comment]
source_id=219 but... this one is largely a duplication of: https://dev.macrostrat.org/burwell/#10/50.3757/-114.2496

**Comment by cambro** [comment]
this source was made obsolete
