### ISSUE TITLE
Kanajuqtuuq (Paquet Bay), NU

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#379]
**Name:**
Saumur, B.M., Skipton, D.R., St-Onge, M.R., Wodicka, N., Bros, E.R., and Weller, O.M., 2018. Bedrock geology, Kanajuqtuuq (Paquet Bay), Nunavut, NTS 37-G north; Geological Survey of Canada, Canadian Geoscience Map 349, scale 1:100 000. https://doi.org/10.4095/306584

**Source URL:**
https://doi.org/10.4095/306584

**Estimated scale:**
large

**Folder name:**
nu_paquet

**Dataset names:**
nu_paquet
nu_paquet_lines
nu_paquet_points

**Number of bedrock polygons:**
140

**Lithology field:**

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**
Strike/trend and dip/plunge in the same columns of nu_paquet_points

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,use_age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nu_paquet where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid,1,name,concat_ws('; ',descrip,concat('location ',d_confiden)),new_type,ST_MakeValid(geom) FROM sources.nu_paquet_lines where new_type is not null and geom is not null;
```
points unclear

**Comment by cvavrus** [comment]
Suggested insert:
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,azimuth,dipplunge,dip_dir,point_type,d_geopoi_1,ST_MakeValid(geom) FROM sources.nu_paquet_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
needed to ST_Force2D lines and points on insert into homogenized tables.
source_id 228
https://dev.macrostrat.org/burwell/#11/71.8608/-78.5100
