### ISSUE TITLE
S Irvine Inlet, NU

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#383]
**Name:**
St-Onge, M.R., Weller, O.M., Dyck, B.J., Rayner, N.M., Chadwick T., and Liikane, D., 2016. Geology, Irvine Inlet (south), Baffin Island, Nunavut; Geological Survey of Canada, Canadian Geoscience Map 262E (preliminary); Canada-Nunavut Geoscience Office, Open File Map 2016-19E, scale 1:100 000. doi:10.4095/297795

**Source URL:**
https://doi.org/10.4095/297795

**Estimated scale:**
large

**Folder name:**
nu_irvine_s

**Dataset names:**
nu_irvine_s
nu_irvine_s_lines
nu_irvine_s_points

**Number of bedrock polygons:**
83

**Lithology field:**

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**
Strike/trend and dip/plunge in the same columns of nu_irvine_s_points

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,use_age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nu_irvine_s where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,1,concat_ws('; ',descrip,concat('location ',d_confiden)),new_type,ST_MakeValid(geom) FROM sources.nu_irvine_s_lines where new_type is not null and geom is not null;
```
points unclear

**Comment by cvavrus** [comment]
Suggested insert:
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,azimuth,dipplunge,dip_dir,point_type,subfeature,ST_MakeValid(geom) FROM sources.nu_irvine_s_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 240
had to force lines and points to 2D on insert.
Also shifted Franklin dike swarm to informal name.
https://dev.macrostrat.org/burwell#10/65.125/-67
