### ISSUE TITLE
Nippers Harbour

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/burwell-processing#385]
**Name:**
Skulski, T; Castonguay, S; Moussallam, Y; McNicoll, V J; van Staal, C R; Bédard, J H. 2015. Geology, Nippers Harbour and parts of Horse Islands, Cape St. John, and Little Bay Island, Newfoundland and Labrador, NTS 2-E/13 and parts of NTS 2-E/12, NTS 2-E/14, and NTS 2-L/4

**Source URL:**
https://geoscan.nrcan.gc.ca/starweb/geoscan/servlet.starweb?path=geoscan/fulle.web&search1=R=295866

**Estimated scale:**
large

**Folder name:**

**Dataset names:**

**Number of bedrock polygons:**

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

**Comments field:**

**Comments:**
This one will require copy-paste from the excel fie

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
**Folder name:**
nl_nippers
**Dataset names:**
nl_nippers
nl_nippers_lines
nl_nippers_points
**Number of bedrock polygons:**
414
**Time field:**
use_age
**Stratigraphy name field:**
strat_name
**Description field:**
descrip
**Comments:**
'Unmapped area' polygon on this map

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,use_age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nl_nippers where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid,1,name,descrip,new_type,ST_MakeValid(geom) FROM sources.nl_nippers_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,azimuth,dipplunge,dip_dir,point_type,comments,ST_MakeValid(geom) FROM sources.nl_nippers_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 236
unmapped areas small random polygons within mapped area, left them in.
https://dev.macrostrat.org/burwell#10/49.885059999999996/-55.731265
