### ISSUE TITLE
Baie Verte

### ISSUE THREAD

**Issue by cambro** [UW-Macrostrat/burwell-processing#386]
**Name:**
Skulski, T; Castonguay, S; Kidd, W S F; McNicoll, V J; van Staal, C R; Hibbard, J P. 2015. Geology, Baie Verte and parts of Fleur de Lys, Newfoundland and Labrador, NTS 12-H/16 and part of NTS 12-I/1

**Source URL:**
https://geoscan.nrcan.gc.ca/starweb/geoscan/servlet.starweb?path=geoscan/fulle.web&search1=R=295865

**Estimated scale:**
large

**Folder name:**

**Dataset names:**

**Number of bedrock polygons:**

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
There are a bunch of good maps here probably:
https://gis.geosurv.gov.nl.ca/minesen/geofiles/default.asp
you should select "All GSC Maps" from menu then enter "bedrock geology"  in keyword, add to search with button, and then search
@cvavrus

**Comment by cvavrus** [comment]
**Folder name:**
nl_baieverte
**Dataset names:**
nl_baieverte
nl_baieverte_lines
nl_baieverte_points
**Number of bedrock polygons:**
653
**Time field:**
use_age
**Stratigraphy name field:**
strat_name
**Description field:**
descrip
**Comments:**
'Unmapped area' polygon on this map

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,use_age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nl_baieverte where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid,1,name,descrip,new_type,ST_MakeValid(geom) FROM sources.nl_baieverte_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,azimuth,dipplunge,dip_dir,point_type,detail,ST_MakeValid(geom) FROM sources.nl_baieverte_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 237
https://dev.macrostrat.org/burwell#10/49.95588/-56.25

expanded point definitions to include igneous layering (called point type "layering")
