### ISSUE TITLE
King's Point, NL

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#387]
**Name:**
Skulski, T., Castonguay, S., Kidd, W.S.F., McNicoll, V.J, and van Staal, C.R., 2015. Geology, King’s Point, Newfoundland and Labrador, NTS 12-H/9; Geological Survey of Canada, Canadian Geoscience Map 156, scale 1:50 000. doi:10.4095/295864

**Source URL:**
https://doi.org/10.4095/295864

**Estimated scale:**
large

**Folder name:**
nl_king

**Dataset names:**
nl_king
nl_king_lines
nl_king_points

**Number of bedrock polygons:**
339

**Lithology field:**

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**
'unmapped area' polygons present

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,use_age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nl_king where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid,1,name,descrip,new_type,ST_MakeValid(geom) FROM sources.nl_king_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,azimuth,dipplunge,dip_dir,point_type,comments,ST_MakeValid(geom) FROM sources.nl_king_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 238
https://dev.macrostrat.org/burwell#10/49.625/-56.25
