### ISSUE TITLE
Mumiksaa-Milne Inlet, NU

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#388]
**Name:**
Saumur, B.M., Skipton, D.R., St-Onge, M.R., Wodicka, N., Bros, E.R., and Weller, O.M., 2018. Bedrock geology, Mumiksaa–Milne Inlet, Nunavut, parts of NTS 38-B and 48-A; Geological Survey of Canada, Canadian Geoscience Map 348, scale 1:100 000. 

**Source URL:**
https://doi.org/10.4095/306579

**Estimated scale:**
large

**Folder name:**
nu_mumiksaa

**Dataset names:**
nu_mumiksaa
nu_mumiksaa_lines
nu_mumiksaa_points

**Number of bedrock polygons:**
77

**Lithology field:**

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,257,map_unit,use_age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nu_mumiksaa where geom is not null;

INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid, 257,name,concat_ws('; ',descrip,concat('location ',d_confiden)),new_type,ST_MakeValid(ST_Force2D(geom)) FROM sources.nu_mumiksaa_lines where new_type is not null and geom is not null;

INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid, 257,azimuth,dipplunge,dip_dir,point_type,concat_ws('; ',comments,d_strucatt),ST_MakeValid(ST_Force2D(geom)) FROM sources.nu_mumiksaa_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 257
https://dev.macrostrat.org/burwell#10/72.27621500000001/-79.55000000000001
