### ISSUE TITLE
Terra Nivea, NU

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#392]
**Name:**
St-Onge, M.R., Rayner, N.M., Steenkamp, H.M., and Gilbert, C., 2015. Geology, Terra Nivea, Baffin Island, Nunavut; Geological Survey of Canada, Canadian Geoscience Map 215E (preliminary); Canada-Nunavut Geoscience Office, Open File Map 2015-02E, scale 1:100 000. doi:10.4095/296104

**Source URL:**
https://doi.org/10.4095/296104

**Estimated scale:**
large

**Folder name:**
nu_terra

**Dataset names:**
nu_terra
nu_terra_lines
nu_terra_points

**Number of bedrock polygons:**
104

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,261,map_unit,age,descrip,strat_name,late_id,early_id,ST_MakeValid(ST_Force2D(geom)) FROM sources.nu_terra where geom is not null;

INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,261,descrip,new_type,ST_MakeValid(ST_Force2D(geom)) FROM sources.nu_terra_lines where new_type is not null and geom is not null;

INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,261,azimuth,dipplunge,dip_dir,point_type,comments,ST_MakeValid(ST_Force2D(geom)) FROM sources.nu_terra_points where point_type is not null and geom is not null;
```

note: most of the lines for this map listed as 'foliation form lines', which I labeled as 'foliation' but you may want to reassess

**Comment by cambro** [comment]
source_id 261
https://dev.macrostrat.org/burwell#10/66.46667/-62.20973
