### ISSUE TITLE
Tebesjuak Lake, NU

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#393]
**Name:**
Peterson, T.D., Scott, J.M.J., LeCheminant, A.N., Chorlton, L.B., D’Aoust, B.M.A., 2014. Geology, Tebesjuak Lake, Nunavut; Geological Survey of Canada, Canadian Geoscience Map 158 (preliminary), scale 1:250 000. doi:10.4095/293892

**Source URL:**
https://doi.org/10.4095/293892

**Estimated scale:**
large

**Folder name:**
nu_tebesjuak

**Dataset names:**
nu_tebesjuak
nu_tebesjuak_lines
nu_tebesjuak_points

**Number of bedrock polygons:**
126

**Lithology field:**
lith_list

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,comments,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,genesis,use_age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nu_tebesjuak where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid,1,name,concat_ws('; ',descrip,concat('location ',confidence)),feature,ST_MakeValid(geom) FROM sources.nu_tebesjuak_lines where geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,strike,dip,dip_dir,point_type,comments,ST_MakeValid(geom) FROM sources.nu_tebesjuak_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
The lith_list field should have been included in lith here. I modified insert to accommodate this. Also, some dips were given as -1, which doesn't make any sense. These points left out.

source_id 253
https://dev.macrostrat.org/burwell#10/63.50032/-99.000155
