### ISSUE TITLE
Geology of Lawrence County Indiana

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#395]
**Name:**

GEOLOGY_OF_LAWRENCE_COUNTY_INDIANA.GDB: Combined 7.5-minute quadrangle bedrock and unconsolidated geologic maps of Lawrence County, Indiana (Indiana Geological Survey, scale 1:48,000, Esri geodatabase)

**Source URL:**

zip of gdb: https://iu.box.com/s/ezlhd981jx8zxspewa0d6zckiotqlpi6

**Estimated scale:**

Large

**Folder name:**

**Dataset names:**

bedrock polygons: GeologicMap/MapUnitPolys
bedrock polygon data:  DescriptionOfMapUnits
quarry polygons:  GeologicMap/OtherPolys
anticline: GeologicMap/ GeologicLines

**Number of bedrock polygons:**
1756

**Lithology field:**

GeneralLithology

**Time field:**

Age

**Stratigraphy name field:**

Name

**Description field:**

Description

**Comments field:**

**Comments:**

This data should be similar to that of https://github.com/UW-Macrostrat/burwell-processing/issues/266
All of the fields listed above are in DescriptionOfMapUnits table and correspond to units named in MapUnitPolys. 
There are some rows with null values in DescriptionOfMapUnits, but those are not associated with a polygon (for instance, if you joined the data from DescriptionOfMapUnits  to the attribute table of  MapUnitPolys on MapUnit, no nulls would come over) . Most of the rows with nulls refer to groups of units, and those units are mapped individually.
The DataSources table has more info on sources listed in the DataSourceID field of the feature layer attribute tables.

OtherPolys shows areas that have been quarried if that's of interest.
GeologLines shows one feature, an anticline in case that was useful too.

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
do you have a full citation and/or link to any relevant publications? Not required, but generally nice. I'm guessing it is this one? https://igws.indiana.edu/bookstore/details.cfm?Pub_Num=DI20

**Comment by ericjohannes** [comment]
@cambro Yep, that's the publication. So the citation would be:
Keith, B. D., Thompson, T. A., Herrmann, E. W., Rupp, R. F., Hasenmueller, W. A., and Johnson, M. R., 2014, GEOLOGY_OF_LAWRENCE_COUNTY_INDIANA.GDB [Esri geodatabase]: Indiana Geological and Water Survey Digital Information 20, scale 1:48,000.

**Comment by ericjohannes** [comment]
A related publication is https://igws.indiana.edu/bookstore/details.cfm?ItemID=2263&Pub_Num=MM90

**Comment by cambro** [comment]
source_id 245
https://dev.macrostrat.org/burwell/#11/38.8448/-86.5266
