### ISSUE TITLE
Circle Lake, NU

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#396]
**Name:**
Sanborn-Barrie, M. and Young, M., 2013. Geology, Circle Lake, Baffin Island, Nunavut; Geological Survey of Canada, Canadian Geoscience Map 5 (preliminary), scale 1:100 000. doi:10.4095/288929

**Source URL:**
https://doi.org/10.4095/288929

**Estimated scale:**
large

**Folder name:**
nu_circle

**Dataset names:**
nu_circle
nu_circle_lines
nu_circle_points

**Number of bedrock polygons:**
131

**Lithology field:**

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**
Quaternary units located in separate .shp file

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,use_age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nu_circle where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,1,descrip,new_type,ST_MakeValid(geom) FROM sources.nu_circle_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,azimuth,dipplunge,dip_dir,point_type,comments,ST_MakeValid(geom) FROM sources.nu_circle_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 247
https://dev.macrostrat.org/burwell#10/66.466665/-64.13325999999999
