### ISSUE TITLE
 Structural Features of Indiana 

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#397]
**Name:**

STRUCTURAL_FEATURES_IN: Structural Features of Indiana (Indiana Geological Survey, Line Shapefile)

**Source URL:**

data: http://maps.indiana.edu/download/Geology/Bedrock_Structural_Features.zip 
metadata: https://maps.indiana.edu/previewMaps/Geology/Bedrock_Structural_Features.html

**Estimated scale:**

medium

**Folder name:**

**Dataset names:**

Bedrock_Structural_Features.zip

**Number of bedrock polygons:**
73 (number of structural feature lines)

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

**Comments field:**

**Comments:**

This dataset has more detail on Indiana's faults than the bedrock map Macrostrat uses for most of the state. That map is from the SGMC, which draws on 
Gray, H.H., Ault, C.H., and Keller, S.J., 1987, Bedrock geologic map of Indiana: Indiana Geological Survey Miscellaneous Map 48, scale 1:500,000.
STRUCTURAL_FEATURES_IN.SHP was last updated in 2013

About this dataset:
The lines are in structural_features_in.shp
in the attribute table, the 'NAME' field has the name, 'Structure' indicates the type of structure (mostly faults), 'SYMBOL' indicates direction of faults' movement and 'Source_Sho' gives the source for each line.

Abstract: STRUCTURAL_FEATURES_IN.SHP is a line shapefile that shows the location of known structural features in Indiana. Attributes include the name of the feature (as listed on the paper source maps), a citation to which paper source source map contained the feature, as well as an indicatior of structural movement of each feature. The paper source maps used to construct these data have scales that range from 1:12,000 to 1:500,000 (only one fault trace) with the majority being taken from sources with a scale of 1:63,360 or larger.

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by aazaff** [comment]
@ericjohannes Add this file to #360 and close this issue.
