### ISSUE TITLE
Sunneshine Fiord, NU

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#398]
**Name:**
Sanborn-Barrie, M., Young, M., Keim, R. and Hamilton, B., 2013. Geology, Sunneshine Fiord, Baffin Island, Nunavut; Geological Survey of Canada, Canadian Geoscience Map 6 (preliminary), scale 1:100 000. doi:10.4095/288931

**Source URL:**
https://doi.org/10.4095/288931

**Estimated scale:**
large

**Folder name:**
nu_sunneshine

**Dataset names:**
nu_sunneshine
nu_sunneshine_lines
nu_sunneshine_points

**Number of bedrock polygons:**
122

**Lithology field:**

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**
Quaternary map units located in a separate .shp file

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,246,map_unit,use_age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom_mod) FROM sources.nu_sunneshine where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid, 246,descrip,new_type,ST_MakeValid(geom) FROM sources.nu_sunneshine_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid, 246,azimuth,dipplunge,dip_dir,point_type,comments,ST_MakeValid(geom) FROM sources.nu_sunneshine_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
This one has some bizarro geometry errors... the NW corner of the map has really messed up geometries and I can't quite figure out how best to fix them. 

A source was added for this one because error wasn't caught until insertion attempt into maps.large: source_id 246

**Comment by cambro** [comment]
I was able to fix this by inspecting the output of:
```
SELECT gid, st_geometrytype(ST_MakeValid((ST_Dump(geom)).geom)), ST_AsText(ST_MakeValid((ST_Dump(geom)).geom)) from sources.nu_sunneshine;
```
One row had ST_GeometryCollection, and one row had ST_LineString. These were the offending geometries.
I then inspected the: ```select gid,st_astext(ST_MakeValid(geom)) from sources.nu_sunneshine;``` output for these two geometries and manually removed the random linestrings and other oddities and redefined the geometries in a geom_mod column. This fixed the problem.

**Comment by cambro** [comment]
source_id 246
https://dev.macrostrat.org/burwell#10/66.46667/-62.20973
