### ISSUE TITLE
Bedrock Geology of Marion County

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#399]
**Name:**

BEDROCK_GEOLOGY_MARIONCO: A map of the bedrock geology of Marion County, Indiana (Indiana Geological Survey, 1:100,000, Polygon shapefile)

**Source URL:**

publication: https://igws.indiana.edu/AllenCounty/Map/
data: https://iu.box.com/s/v1ris2b0lvhpz0ao79fncm92ef8yivwi

**Estimated scale:**

large

**Folder name:**

**Dataset names:**

shapefile/MarionCo_BedrockGeology.shp

**Number of bedrock polygons:**
6

**Lithology field:**

**Time field:**

Age

**Stratigraphy name field:**

Bedrock_Un

**Description field:**

Descriptio

**Comments field:**

**Comments:**

The field 'Descriptio' contains lithology information
All the polygons are in MarionCo_BedrockGeology.shp. That file and all the files associated with it are in the folder 'shapefile'  
'BEDROCK_GEOLOGY_MARIONCO.txt' has metadata about this map.

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
links in description were removed because they were non-specific (i.e., they were all the same and would require a user to type a search string into a form in order to see any information about the unit). If the survey wishes to create a RESTful service for this (i.e., where each record is uniquely identified by a URL) then we can add links.

**Comment by cambro** [comment]
source_id 250
https://dev.macrostrat.org/burwell/#12/39.7787/-86.1392

**Comment by ericjohannes** [comment]
@cambro Oops, no, there's no need to add links. I thought we'd cleaned those out of the attribute table.
