### ISSUE TITLE
Bedrock Surface Contours of Indiana

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#403]
**Name:**

BEDROCK_SURFACE_250K_IGS_IN: Bedrock Surface Contours of Indiana (Indiana Geological Survey, 1:250,000, Line Shapefile)

**Source URL:**

http://maps.indiana.edu/download/Geology/Bedrock_Surface_Contours.zip

**Estimated scale:**

medium

**Folder name:**

**Dataset names:**

lines: Bedrock_Surface_250k_IGS_IN.shp
metadata: Bedrock_Surface_250k_IGS_IN.txt
**Number of bedrock polygons:**

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

**Comments field:**

**Comments:**

the 'Contour' field has the elevation of the bedrock in feet

This is not a straightforward bedrock geology map so I'm including the abstract here thinking that might help:

Abstract: BEDROCK_SURFACE_250K_IGS_IN.SHP is an Esri line shapefile providing a contoured depiction of the bedrock surface elevation of Indiana. Surface contours are represented by polylines (50 foot contour interval) each with a single value that provides estimated elevation of bedrock surface in feet.

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by aazaff** [comment]
@ericjohannes This is very useful data, but please append it to #360 and close this issue.
