### ISSUE TITLE
Unconsolidated Thickness Contours of Indiana 

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#404]
**Name:**

UNCONSOLIDATED_THICKNESS_250K_IGS_IN.SHP: Unconsolidated Thickness Contours of Indiana (Indiana Geological Survey, 1:250,000, Line Shapefile)

**Source URL:**

http://maps.indiana.edu/download/Geology/Surficial_Unconsolidated_Thickness_Contours.zip

**Estimated scale:**

medium

**Folder name:**

**Dataset names:**

data: Unconsolidated_Thickness_250k_IGS_IN.shp
metadata: Unconsolidated_Thickness_250k_IGS_IN.txt
**Number of bedrock polygons:**

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

**Comments field:**

**Comments:**

This is not a straightforward bedrock geology map so I'm including the abstract here thinking that might help:

UNCONSOLIDATED_THICKNESS_250k_IGS_IN.SHP is an Esri line shapefile providing a contoured depiction of the thickness of unconsolidated sediments in Indiana. Thickness contours are represented by polylines (50 foot contour interval) each with a single value that provides estimated thickness of unconsolidated deposits in feet.

the 'Contour (feet)' field has the thickness of the sediment in feet

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by aazaff** [comment]
@ericjohannes Let's roll this in with #360 and close this issue.
