### ISSUE TITLE
Calder River, NWT

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#406]
**Name:**
Hildebrand, R.S., Bowring, S.A., and Pelletier, K.S., 2014. Geology, Calder River,
Northwest Territories, NTS 86-F; Geological Survey of Canada, Canadian Geoscience
Map 154 (preliminary); Northwest Territories Geoscience Office, NWT Open Report
2013-003, scale 1:125 000. doi:10.4095/292861

**Source URL:**
https://doi.org/10.4095/292861

**Estimated scale:**
large

**Folder name:**
nwt_calder

**Dataset names:**
nwt_calder
nwt_calder_lines
nwt_calder_points

**Number of bedrock polygons:**
1104

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nwt_calder where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,1,descriptio,new_type,ST_MakeValid(geom) FROM sources.nwt_calder_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,azimuth,dipplunge,dip_dir,point_type,struc_type,ST_MakeValid(geom) FROM sources.nwt_calder_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 265
https://dev.macrostrat.org/burwell/#10/65.6597/-117.0985
