### ISSUE TITLE
Epicenters of Earthquakes in Indiana with a Moment Magnitude Equal to or Greater Than 3.0

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#407]
**Name:**

EARTHQUAKE_EPICENTERS_IN: Epicenters of Earthquakes in Indiana with a Moment Magnitude Equal to or Greater Than 3.0 (Indiana Geological Survey, 1:500,000, Point Shapefile)

**Source URL:**

http://maps.indiana.edu/download/Geology/Seismic_Earthquake_Epicenters.zip
http://maps.indiana.edu/previewMaps/Geology/Seismic_Earthquake_Epicenters.html

**Estimated scale:**

medium

**Folder name:**

**Dataset names:**

points: Earthquake_Epicenters_IN.shp
metadata: Earthquake_Epicenters_IN.txt

**Number of bedrock polygons:**
44 (points)

**Lithology field:**

**Time field:**

Year
Month
Day
Hour 
Minute
Seconds

**Stratigraphy name field:**

**Description field:**

Magnitude

**Comments field:**

Depth (km below surface)

**Comments:**

Abstract:
EARTHQUAKE_EPICENTERS_IN.SHP shows the locations of all known historical earthquakes in Indiana with a moment magnitude (Mw) greater than or equal to 3.0. It includes earthquake locations derived from both instrumented recordings and estimations from historical accounts. The shapefile is an amalgam of points created from the CEUS SSC catalog maintained by the U.S. Nuclear Regulatory Commission (up to December 31, 2008) and the U.S. Geological Survey, National Earthquake Information Center (three events on December 30, 2010, January 26, 2012, and May 10, 2012). Values of Moment Magnitude (Mw) are used in this data. Mw refers to the energy released by the event, which is proportional to the slip on a fault multiplied by the area of the fault surface that slips. Events below Mw 3.0 have been omitted, as those events are below the energies felt by humans. Also, all pre-shock and aftershock, non-tectonic (e.g., mine blast), and duplicate event entries have been omitted. Data attributes include event date and time, x-y coordinate locations, and Moment Magnitude (Mw) values.

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by aazaff** [comment]
This looks like it would be a fun one for us to do for Flyover, but there are plenty of other EQ data streams that flyover could tap into. So let's not do this one.
