### ISSUE TITLE
Abandoned Quarries in Indiana

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#408]
**Name:**

Hasenmueller, W.A., and Ault, C.H., 2001, Abandoned Industrial Minerals Quarries in Indiana, 2nd Edition, Digital Version, Computer Database 2, Indiana Geological Survey.

**Source URL:**

data: http://maps.indiana.edu/download/Geology/Industrial_Minerals_Quarries_Abandoned.zip
map: http://maps.indiana.edu/previewMaps/Geology/Industrial_Minerals_Quarries_Abandoned.html

more data: https://iu.box.com/s/26usoc9xmpeonesu4jegpmmkbawfd4s4
**Estimated scale:**

medium

**Folder name:**

**Dataset names:**

data: Quarries_Abandoned_IN.shp
metadata: Quarries_Abandoned_IN.txt

in the zipped file at the "more data" link:
data/QUASTR.TXT has stratigraphy info
data/QUAHIS.TXT has info on the companies that operated each quarry and what it produced

**Number of bedrock polygons:**
1071 (points)

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

**Comments field:**

Has three fields with more information:
Total Production (short tons)
Average Thickness of Quarried Rock Unit (feet)
Elevation of Stratigraphic Marker (feet)

**Comments:**

the folder at the "more data" link has more information related to this map including stratigraphy of those mines, companies that operated them and what the mines produced. That is all in the 'Data" subfolder.
The first value in the TXT files, which have comma-separated values, is an ID that corresponds to "IGS ID (Database #2) in the shapefile. These relationships are explained in report/Database2.pdf

Abstract:
QUARRIES_ABANDONED_IN was derived from a comma-delimited text file named "QUALOC.TXT" contained on the following CD-ROM publication: Hasenmueller, W.A., and Ault, C.H., 2001, Abandoned Industrial Minerals Quarries in Indiana, 2nd Edition, Digital Version, Computer Database 2, Indiana Geological Survey. The field named "QUANUM" can be used to link this data to the following tables available in the publication cited above: bibliography (QUAREF.TXT), history of operation (QUAHIS.TXT), and stratigraphy (QUASTR.TXT). It contains all abandoned quarry locations within QUALOC.TXT that have locational information that is adequate to determine UTM coordinate values.

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by aazaff** [comment]
@ericjohannes Roll this into #413 and close this issue please.
