### ISSUE TITLE
Petroluem Fields (2015) (Indiana)

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#409]
**Name:**

PETROLEUM_FIELDS_IGS_IN.SHP: Petroleum Reservoir Fields (Oil and Gas) in Indiana (Indiana Geological Survey, 1:63,360, Polygon Shapefile)

**Source URL:**

data: http://maps.indiana.edu/download/Geology/Petroleum_Fields.zip
metadata: https://maps.indiana.edu/metadata/Geology/Petroleum_Fields.html

**Estimated scale:**

medium

**Folder name:**

**Dataset names:**

Petroleum_Fields_IGS_IN.shp

**Number of bedrock polygons:**
627 (petroleum field polygons)

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

Type (G = petroleum field consisting of Gas production, O  =  petroleum field consisting of Oil production, OG =petroleum field consisting of Oil and Gas production)

**Comments field:**

**Comments:**

Abstract:
PETROLEUM_FIELDS_IGS_IN.SHP is an Esri polygon shapefile that depicts the locations and extents of all petroleum reservoir fields in Indiana, as of January 8, 2015. PETROLEUM_FIELDS_IGS_IN.SHP shows boundaries of petroleum reservoir fields that enclose petroleum wells that are classified as producing from a single field, but does not necessarily indicate the maximum extent of the producing reservoir field.

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by aazaff** [comment]
Let's not do this one.
