### ISSUE TITLE
Petroleum Well Locations in Indiana

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#411]
**Name:**

PETROLEUM_WELLS_IGS_IN.SHP: Petroleum Well Locations in Indiana (Indiana Geological Survey, 1:24,000, Point Shapefile)

**Source URL:**

http://maps.indiana.edu/download/Geology/Petroleum_Wells.zip

**Estimated scale:**

medium

**Folder name:**

**Dataset names:**

data: Petroleum_Wells_IGS_IN.shp
metadata: Petroleum_Wells_IGS_IN.txt
**Number of bedrock polygons:**

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

Alt_Symbol

**Comments field:**

**Comments:**

Other fields:
POSTED_TD - The deepest total depth of any operation conducted on a well. For deviated wells (horizontal and directional wells), the value has been corrected to true vertical depth. The value is retrieved from a query of the TD data field in the Well Events Table and from the Pick TVD value in the Picks Table in the Records for Event Section. The posted TD is the total depth that is posted by the IGS on a map showing total depths. (Note: A value of "zero" indicates no data.)
FIELD_NAME

Abstract:
PETROLEUM_WELLS_IGS_IN.SHP is an ESRI ArcGIS point shapefile of locations of all known petroleum test wells in Indiana as of January 8, 2015, as contained in the Indiana Geological Survey's Petroleum Well Database. The IGS has limited the attribute information contained in these data to the following; well identification numbers, total well depth, well type symbols (well description), and the oil/gas field names. If users require more detailed information regarding well record tables or petroleum field production histories please visit the IGS Petroleum Database Management System (PDMS): ( <http://igs.indiana.edu/PDMS/> ).
The PDMS Web site is comprised of an interactive map that offers users the ability to examine and build customized maps, query data, and interactively link to a "Table Viewer," where detailed tables provide well header and event information, as well as production histories, etc. The PDMS is a subscription-based Web site, where users can choose to view petroluem records and maps at no cost using the "Basic Subscription" option. The PDMS "Premium Subscription" option does charge a fee, but adds even more value to well records, reports, logs, and geological interpretations related to a well. It also allows for more efficient access to data from multiple wells during a single user session. If users require more detailed information regarding well record tables or petroleum field production histories please visit the IGS Petroleum Database Management System (PDMS): ( <http://igs.indiana.edu/PDMS/> ).
## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by aazaff** [comment]
Let's not do this one.
