### ISSUE TITLE
Southern extent of glaciation in Indiana

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#416]
**Name:**

PRE-WISCONSIN_GLACIAL_LIMIT_IN: Southern extent of glaciation in Indiana (Indiana Geological Survey, 1:500,000, Line Shapefile)

**Source URL:**

http://maps.indiana.edu/download/Geology/Glacial_PreWisconsin_Glacial_Limit.zip

**Estimated scale:**

medium

**Folder name:**

**Dataset names:**

data: PRE-WISCONSIN_GLACIAL_LIMIT_IN.shp
metadata: PRE-WISCONSIN_GLACIAL_LIMIT_IN.txt

**Number of bedrock polygons:**
1 (line)

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

**Comments field:**

Limit - Identification of feature represented in the data layer.

**Comments:**

Abstract:
PRE-WISCONSIN_GLACIAL_LIMIT_IN.shp is a line shapefile that shows the extent of glaciation in Indiana as delineated by mapped glacial deposits of various types and ages at a scale of 1:500,000. The mapped units include Pleistocene sediments of glacial origin that are interpreted to have been deposited during multiple episodes of continental glaciation by the North American Laurentide ice sheet. The term "pre-Wisconsin" is meant to distinguish this glacial limit from that represented in a companion data set [WISCONSIN_GLACIAL_LIMIT_IN: Extent of Wisconsin Glaciation in Indiana (Indiana Geological Survey, 1:500,000, Line Shapefile)] that represents the (later or younger) limit of Wisconsin glaciation in Indiana.

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by aazaff** [comment]
Let's not do this one.
