### ISSUE TITLE
Extent of Wisconsin glaciation in Indiana

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#418]
**Name:**

WISCONSIN_GLACIAL_LIMIT_IN: Extent of Wisconsin glaciation in Indiana (Indiana Geological Survey, 1:500,000, Line Shapefile)

**Source URL:**

http://maps.indiana.edu/download/Geology/Glacial_Wisconsin_Glacial_Limit.zip

**Estimated scale:**

medium

**Folder name:**

**Dataset names:**

data: WISCONSIN_GLACIAL_LIMIT_IN.shp
metadata: WISCONSIN_GLACIAL_LIMIT_IN.txt

**Number of bedrock polygons:**
71 (lines)

**Lithology field:**

**Time field:**

Geol_age

**Stratigraphy name field:**

**Description field:**

Symbol (gap = Inferred location of glacial limit; connects known locations of glacial till deposits of Wisconsin age., ma = Loam till interpreted to be deposited by the Huron-Erie ice lobe., mv = Loam till interpreted to be deposited by the Lake Michigan ice lobe., ta = Loam till interpreted to be deposited by the Huron-Erie ice lobe., tb = Loam till interpreted to be deposited by the Huron-Erie ice lobe., tv = Loam till interpreted to be deposited by the Lake Michigan ice lobe. )
**Comments field:**

Limit - Identification of mapped versus inferred glacial limit line segments.

**Comments:**

Abstract:
WISCONSIN_GLACIAL_LIMIT_IN.shp is a line shapefile that shows the Wisconsin glacial limit in Indiana as delineated by mapped glacial deposits at a scale of 1:500,000. The mapped units include glacial till that is interpreted to have been deposited during the Wisconsin Glaciation. The last major expansion of the North American Laurentide Ice Sheet occured in the Wisconsin glacial episode.

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by aazaff** [comment]
Let's not do this one.
