### ISSUE TITLE
Silurian Reef Locations in Indiana

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#419]
**Name:**

SILURIAN_REEF_POINTS_MM54_IN: Silurian Reef Locations in Indiana (Indiana Geological Survey, 1:500,000, Point Shapefile)

**Source URL:**

data: http://maps.indiana.edu/download/Geology/Silurian_Reefs_Points.zip
metadata: http://maps.indiana.edu/previewMaps/Geology/Silurian_Reefs_Points.html

**Estimated scale:**

medium

**Folder name:**

**Dataset names:**

SILURIAN_REEF_POINTS_MM54_IN.SHP

**Number of bedrock polygons:**
444 (points)

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

**Description field:**

Legend

**Comments field:**

Field - Oil, gas and gas storage field name associated with reef-induced structures

**Comments:**

Abstract:
SILURIAN_REEF_POINTS_MM54_IN is a point shapefile that shows the locations of Silurian rock reef formations in Indiana. These data include five categories: (1) buried reef masses, (2) exposed reef, (3) exposed reef in active stone quarries, (4) reef-induced structure in overlying rocks, and (5) reef-induced structure in overlying rocks related to oil, gas, and gas storage fields.
This shapefile can be used in conjunction with SILURIAN_REEF_POLYGONS_MM54_IN.

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by aazaff** [comment]
@ericjohannes Merge this back with #420 then close
