### ISSUE TITLE
S Chidliak Bay, NU

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#422]
**Name:**
Steenkamp, H.M., Gilbert, C., and St-Onge, M.R., 2016. Geology, Chidliak Bay (south), Baffin Island, Nunavut, NTS 26-B (south); Geological Survey of Canada, Canadian Geoscience Map 272 (preliminary); Canada-Nunavut Geoscience Office, Open File Map 2016-08, scale 1:100 000. doi:10.4095/297357

**Source URL:**
https://doi.org/10.4095/297357

**Estimated scale:**
large

**Folder name:**
nu_chidliak_s

**Dataset names:**
nu_chidliak_s
nu_chidliak_s_lines

**Number of bedrock polygons:**
103

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**
unmapped area polygon present
There was an error importing the points .shp file into Postico

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nu_chidliak_s where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,1,descrip,new_type,ST_MakeValid(geom) FROM sources.nu_chidliak_s_lines where new_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id = 264
https://dev.macrostrat.org/burwell#10/64.25/-67
