### ISSUE TITLE
Locations of Operation for Active Industrial Minerals Producers in 2016 in Indiana

### ISSUE THREAD

**Issue by ericjohannes** [UW-Macrostrat/burwell-processing#423]
**Name:**

INDUSTRIAL_MINERALS_ACTIVE_2016_IN.SHP: Locations of Operation for Active Industrial Minerals Producers in 2016 in Indiana (Indiana Geological Survey, Point Shapefile)

**Source URL:**

http://maps.indiana.edu/download/Geology/Industrial_Minerals_Sites_2016.zip

**Estimated scale:**

medium

**Folder name:**

**Dataset names:**

data: INDUSTRIAL_MINERALS_ACTIVE_2016_IN.SHP
metadata: INDUSTRIAL_MINERALS_ACTIVE_2016_IN.txt

**Number of bedrock polygons:**
286 (points)

**Lithology field:**

**Time field:**

**Stratigraphy name field:**

Geology - Stratigraphic units produced at the mine/plant, and thicknesses, where known

**Description field:**

**Comments field:**

Commodity - Mineral commodity produced at the mine/plant
Company_Na - Name of the company that owns the mine/plant
Remarks - General comments regarding the mine/plant
Mine_Plant -  Name by which the mine/plant is known
Products - Description of products produced by the mine/plant

**Comments:**

Abstract:
INDUSTRIAL_MINERALS_ACTIVE_2016_IN.SHP is a point shapefile that shows the locations of operation for industrial minerals producers that were active in 2016 in Indiana. These operations extract and (or) produce the following commodities: cement, clay and shale, crushed stone, dimension limestone, dimension sandstone, gypsum, lime, peat, slag, and sand and gravel. The data set contains location, contact information, geologic information, and other relevant information for all industrial minerals operations known to be active in Indiana on 20160415.

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by aazaff** [comment]
@ericjohannes Let's roll this into #413, let's basically make one big economic geo map. Close this issue after please.
