### ISSUE TITLE
S Sylvia Grinnell Lake NU

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#427]
**Name:**
Geology, Sylvia Grinnell Lake (south), Baffin Island, Nunavut; St-Onge, M R; Weller, O M; Dyck, B J; Rayner, N M; Chadwick, T; Liikane, D. Geological Survey of Canada, Canadian Geoscience Map 254S, (ed. prelim.), 2016, 1 sheet, https://doi.org/10.4095/298757

**Source URL:**
Ihttps://doi.org/10.4095/298757

**Estimated scale:**
large

**Folder name:**
nu_sylvia_s

**Dataset names:**
nu_sylvia_s
nu_sylvia_s_lines
nu_sylvia_s_points

**Number of bedrock polygons:**
30

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
geo_desc

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by rleverett** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,266,name,age,geo_desc,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nu_sylvia_s where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid, 266,descrip,new_type,ST_MakeValid(geom) FROM sources.nu_sylvia_s_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid, 266,azimuth,dipplunge,dip_dir,point_type,comments,ST_MakeValid(geom) FROM sources.nu_sylvia_s_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 266
https://dev.macrostrat.org/burwell#10/64.25/-69
