### ISSUE TITLE
Western Australia

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#438]
**Name:**
Geological Survey of Western Australia, 2016, 1:500 000 State interpreted bedrock geology of Western Australia, 2016: Geological
Survey of Western Australia, digital data layer, www.dmp.wa.gov.au/geoview.
Compilers of geology: DMcB Martin, SP Johnson, and A Riganti
Compiler GIS: J Hogen-Esch
Editor: SR White

**Source URL:**
http://dmpbookshop.eruditetechnologies.com.au/product/1500-000-state-interpreted-bedrock-geology-of-western-australia-2016.do

**Estimated scale:**
medium

**Folder name:**
aus_wa

**Dataset names:**
aus_wa
aus_wa_lines

**Number of bedrock polygons:**
18065

**Lithology field:**
lith_list

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descriptn

**Comments field:**

**Comments:**

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,lith,t_interval,b_interval,comments,geom) 
SELECT gid,1,unitname,use_age,descriptn,strat_name,lith_list,late_id,early_id,comments,ST_MakeValid(geom) FROM sources.aus_wa where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid,1,type,name,new_type,ST_MakeValid(geom) FROM sources.aus_wa_lines where new_type is not null and geom is not null;
```
Also, this map had the cenozoic units on a separate .shp file, should I process that map as well @cambro ?

**Comment by cambro** [comment]
will probably put this one on hold due to high quality of more recent 1:1M map
