### ISSUE TITLE
Grinnell Glacier, NU

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#442]
**Name:**
Geology, Grinnell Glacier, Baffin Island, Nunavut; St-Onge, M R; Rayner, N M; Steenkamp, H M; Gilbert, C. Geological Survey of Canada, Canadian Geoscience Map 217E, (ed. prelim.), 2015, 1 sheet

**Source URL:**
https://doi.org/10.4095/296111

**Estimated scale:**
large

**Folder name:**
nu_grinnell

**Dataset names:**
nu_grinnell
nu_grinnell_lines
nu_grinnell_points

**Number of bedrock polygons:**
543

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
geo_descri

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by rleverett** [comment]
Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,name,age,geo_descri,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nu_grinnell where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid,1,geolinetyp,qualifier,new_type,ST_MakeValid(geom) FROM sources.nu_grinnell_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,azimuth,dipplunge,dip_dir,point_type,geopointty,ST_MakeValid(geom) FROM sources.nu_grinnell_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 269
needed to modify the insert statements
https://dev.macrostrat.org/burwell#10/62.875/-67.460195
