### ISSUE TITLE
Goulburn, New South Wales

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#443]
**Name:**
O.D. Thomas, D.J. Pogson, A.J. Johnston, M.M. Scott, A.Y.E. Warren, L. Sherwin, G.P. Colquhoun, J.J. Watkins, R.G. Cameron, G.P. MacRae, R.A. Glen & J.J. Vassallo. 2013. Goulburn 1:250 000 Geological Sheet SI/55-12, 2nd edition. (2 sheets). Geological Survey of New South Wales, Maitland

**Source URL:**
https://search.geoscience.nsw.gov.au/product/172

**Estimated scale:**
large

**Folder name:**
nsw_goul

**Dataset names:**
nsw_goul
nsw_goul_lines
nsw_goul_points

**Number of bedrock polygons:**
5133

**Lithology field:**

**Time field:**
system

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,system,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_goul where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid,1,descrip,strucname,new_type,ST_MakeValid(geom) FROM sources.nsw_goul_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,azimuth,dip,dip_dir,point_type,concat_ws('; ',codedescpt,comments),ST_MakeValid(geom) FROM sources.nsw_goul_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 270
https://dev.macrostrat.org/burwell#10/-34.50013/149.24997000000002
I needed to clean up '?' in descriptions and some ages. Some point types needed revision.
