### ISSUE TITLE
S Ellef Ringnes Island, NU

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#457]
**Name:**
Geology, Ellef Ringnes Island south, Nunavut; Evenchick, C A; Embry, A F. Geological Survey of Canada, Canadian Geoscience Map 87, (ed. prelim.), 2012, 1 sheet

**Source URL:**
https://doi.org/10.4095/291566

**Estimated scale:**
large

**Folder name:**
nu_ellef_s

**Dataset names:**
nu_ellef_s
nu_ellef_s_lines
nu_ellef_s_points

**Number of bedrock polygons:**
925

**Lithology field:**

**Time field:**
max_age, min_age

**Stratigraphy name field:**
strat_name

**Description field:**
descriptio

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by rleverett** [comment]
A lot of unmapped items in this map
Some of the labels in the polygons were unclear and were not connected to a specific time period on the PDF

Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,lith,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,271,name,use_age,lith_list,new_descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nu_ellef_s where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid,271,initcap(name),descrip,new_type,ST_MakeValid(geom) FROM sources.nu_ellef_s_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,271,strike,dip,dip_dir,trend,plunge,point_type,concat_ws('; ',subfeature,remarks),ST_MakeValid(geom) FROM sources.nu_ellef_s_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
This one had a few processing errors. Let's go over this together @rleverett

**Comment by cambro** [comment]
source_id 271
https://dev.macrostrat.org/burwell#10/78.523685/-102.280485
