### ISSUE TITLE
Gosford-Lake Macquarie, New South Wales

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#460]
**Name:**
Och D.J., Jones D.C., Uren R.E. & Hughes K.S. (compilers) 2015. Gosford-Lake Macquarie Special 1:100 000 Geological Sheet 9131 & part sheet 9231. First Edition. Geological Survey of New South Wales, Maitland.

**Source URL:**
https://search.geoscience.nsw.gov.au/product/9084

**Estimated scale:**
large

**Folder name:**
nsw_gosford

**Dataset names:**
nsw_gosford
nsw_gosford_lines
nsw_gosford_points

**Number of bedrock polygons:**
625

**Lithology field:**
dom_lith

**Time field:**
age_range

**Stratigraphy name field:**
strat_name

**Description field:**
descriptio

**Comments field:**
dep_env

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,comments,t_interval,b_interval,geom) 
SELECT gid,267,unit_nam,age_range,descriptio,strat_name,dep_env,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_gosford where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid,1,concat_ws('; ',codedescpt,descrptn),strucname,new_type,ST_MakeValid(geom) FROM sources.nsw_gosford_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,strike,dip,azimuth,point_type,concat_ws('; ',codedescpt,comments),ST_MakeValid(geom) FROM sources.nsw_gosford_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 267
https://dev.macrostrat.org/burwell#10/-33.25/151.375
