### ISSUE TITLE
Bathurst, New South Wales

### ISSUE THREAD

**Issue by cvavrus** [UW-Macrostrat/burwell-processing#469]
**Name:**
Watkins J.J., Pogson D.J., Hawley S.P. and Henderson G.A.M., 1997, Bathurst 1:100 000 First Edition (1:100,000 geological map 8831) Geological Survey of New South Wales, Sydney / Australian Geological Survey Organisation, Canberra.

**Source URL:**
https://search.geoscience.nsw.gov.au/product/43

**Estimated scale:**
large

**Folder name:**
nsw_bathurst

**Dataset names:**
nsw_bathurst
nsw_bathurst_lines
nsw_bathurst_points

**Number of bedrock polygons:**
481

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
desc

**Comments field:**

**Comments:**
no strike/dip info was included in the points file

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cvavrus** [comment]
Suggested inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,age,lith_desc,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_bathurst where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,1,"desc",new_type,ST_MakeValid(geom) FROM sources.nsw_bathurst_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,point_type,comments,geom) 
SELECT gid,1,point_type,"desc",ST_MakeValid(geom) FROM sources.nsw_bathurst_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 273
points weren't relevant for import.
https://dev.macrostrat.org/burwell#10/-33.248435/149.75115499999998
