### ISSUE TITLE
Boorowa, NSW

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#474]
**Name:**
Johnston A.J., Pogson D.J., Thomas O.D., Watkins J.J. and Glen R.A., 2013, Boorowa 1:100 000 Geological Sheet 8629, 1st edition. Geological Survey of New South Wales, Maitland.

**Source URL:**
https://search.geoscience.nsw.gov.au/product/49

**Estimated scale:**
large

**Folder name:**
nsw_boorowa

**Dataset names:**
nsw_boorowa
nsw_boorowa_lines
nsw_boorowa_points

**Number of bedrock polygons:**
3240

**Lithology field:**

**Time field:**
age_

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by rleverett** [comment]
Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,272,unitname,age_,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_boorowa where geom is not null;

INSERT INTO lines.large (orig_id,source_id,name,descrip,new_type,geom) 
SELECT gid, 272,strucname,codedescpt,new_type,ST_MakeValid(geom) FROM sources.nsw_boorowa_lines where new_type is not null and geom is not null;

INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid, 272,strike,dip,azimuth,point_type,codedescpt,ST_MakeValid(geom) FROM sources.nsw_boorowa_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
source_id 272
This one needed a few minor modifications. Be sure to get the line name if there is one (e.g., San Andreas Fault) and make sure all map polygons have a unit name (even if you have to add your best description based on map image in pdf/jget).

I inserted this one, but it overlaps with another map, source_id 270. It's good to check for overlap and prioritize maps that do not overlap at first.
