### ISSUE TITLE
Gulgong, New South Wales

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#480]
**Name:**
Watkins J.J., Cameron R.G., Yoo E.K. and Colqhoun G.P., 2000, Gulgong 1:100 000 Geological Sheet 8833, 1st edition. Geological Survey of New South Wales, Sydney & Geoscience Australia, Canberra

**Source URL:**
https://search.geoscience.nsw.gov.au/product/93

**Estimated scale:**
large

**Folder name:**
nsw_gulgong

**Dataset names:**
nsw_gulgong
nsw_gulgong_lines
nsw_gulgong_points

**Number of bedrock polygons:**
577

**Lithology field:**

**Time field:**

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by rleverett** [comment]
There was no strike/dip information in the points files

Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,unitname,age_,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_gulgong where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid,1,descriptio,feat_name,new_type,ST_MakeValid(geom) FROM sources.nsw_gulgong_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,point_type,comments,geom) 
SELECT gid,1,point_type,descriptio,ST_MakeValid(geom) FROM sources.nsw_gulgong_points where point_type is not null and geom is not null;
```

**Comment by kaakin** [comment]
Processed during the initial round of candidates processing by Kate. (map_ingestion->sources)
-Only Polygons Processed?
