### ISSUE TITLE
Hillston, New South Wales

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#481]
**Name:**
Colqhoun G.P., Cameron R.G. and Meakin N.S., 2008, Hillston 1:100 000 Geological Sheet 8031, 1st edition. Geological Survey of New South Wales, Sydney.

**Source URL:**
https://search.geoscience.nsw.gov.au/product/95

**Estimated scale:**
large

**Folder name:**
nsw_hillston

**Dataset names:**
nsw_hillston
nsw_hillston_lines
nsw_hillston_points

**Number of bedrock polygons:**
512

**Lithology field:**

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by rleverett** [comment]
Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,main_name,use_age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_hillston where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,1,descriptio,new_type,ST_MakeValid(geom) FROM sources.nsw_hillston_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,azimuth,dip,dip_dir,point_type,subtype,ST_MakeValid(geom) FROM sources.nsw_hillston_points where point_type is not null and geom is not null;
```

**Comment by kaakin** [comment]
Processed during the initial round of candidates processing by Kate. (map_ingestion->sources)
-Only Polygons Processed?
