### ISSUE TITLE
Mt Arrowsmith, New South Wales

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#484]
**Name:**
Greenfield, J.E. and Reid, W.J. 2010 Mount Arrowsmith 1:100 000 Geological Sheet 7237, First edition. Geological Survey of New South Wales, Maitland

**Source URL:**
https://search.geoscience.nsw.gov.au/product/8

**Estimated scale:**
large

**Folder name:**
nsw_mtarrowsmith

**Dataset names:**
nsw_mtarrowsmith
nsw_mtarrowsmith_lines
nsw_mtarrowsmith_points

**Number of bedrock polygons:**
1134

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
stratdes

**Comments field:**

**Comments:**

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by rleverett** [comment]
Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,age,stratdes,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_mtarrowsmith where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid,1,codedescpt,strucname,new_type,ST_MakeValid(geom) FROM sources.nsw_mtarrowsmith_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,azimuth,dip,dip_dir,point_type,codedescpt,ST_MakeValid(geom) FROM sources.nsw_mtarrowsmith_points where point_type is not null and geom is not null;
```

**Comment by kaakin** [comment]
Processed during the initial round of candidates processing by Kate. (map_ingestion->sources)
