### ISSUE TITLE
Parkes, New South Wales

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#488]
**Name:**
Raymond O.L., Sherwin L., Wallace D.A., Wyborn D., Young G.C. and Percival I.G., 2000, Parkes 1:100 000 Geological Sheet 8531, 1st edition. Geological Survey of New South Wales, Sydney & Geoscience Australia, Canberra

**Source URL:**
https://search.geoscience.nsw.gov.au/product/129

**Estimated scale:**
large

**Folder name:**
nsw_parkes

**Dataset names:**
nsw_parkes
nsw_parkes_lines
nsw_parkes_points

**Number of bedrock polygons:**
669

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
lith_desc

**Comments field:**

**Comments:**

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by rleverett** [comment]
Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,unitname,age,lith_desc,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_parkes where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid,1,desc_,name,new_type,ST_MakeValid(geom) FROM sources.nsw_parkes_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,strike,inclinatio,azimuth,point_type,legend,ST_MakeValid(geom) FROM sources.nsw_parkes_points where point_type is not null and geom is not null;
```

**Comment by kaakin** [comment]
Processed during the initial round of candidates processing by Kate. (map_ingestion->sources)
