### ISSUE TITLE
Sussex, New South Wales

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#491]
**Name:**
Burton G.R., Trigg S.J. & Dawson M.W. Sussex 1:100 000 Geological Sheet 8135, First edition. Geological Survey of New South Wales, Maitland, NSW.
--

**Source URL:**
https://search.geoscience.nsw.gov.au/product/134

**Estimated scale:**
large

**Folder name:**
nsw_sussex

**Dataset names:**
nsw_sussex
nsw_sussex_lines
nsw_sussex_points

**Number of bedrock polygons:**
2382

**Lithology field:**

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descriptio

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by rleverett** [comment]
Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,285,unit_name,use_age,descriptio,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_sussex where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid, 285,codedescpt,strucname,new_type,ST_MakeValid(geom) FROM sources.nsw_sussex_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid, 285,strike,dip,dip_dir,point_type,codedescpt,ST_MakeValid(geom) FROM sources.nsw_sussex_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
The strike and dip on the points required major changes. The "azimuth" was the dip direction. strike therefore needed to be computed from that.

**Comment by cambro** [comment]
source_id 285
https://dev.macrostrat.org/burwell/#11/-31.2604/146.3914
