### ISSUE TITLE
Inuvik, NWT

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#495]
**Name:**
Geology, Inuvik, Northwest Territories; Cecile, M P; Lane, L S; Dyke, L D; Norris, D K. Geological Survey of Canada, Canadian Geoscience Map 178, (ed. prelim.), 2015, 1 sheet

**Source URL:**
https://doi.org/10.4095/295655

**Estimated scale:**
large

**Folder name:**
nwt_inuvik

**Dataset names:**
nwt_inuvik
nwt_inuvik_lines
nwt_inuvik_points

**Number of bedrock polygons:**
25

**Lithology field:**

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by rleverett** [comment]
No planar points.

Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,map_unit,use_age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nwt_inuvik where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid,1,feature,subfeature,new_type,ST_MakeValid(geom) FROM sources.nwt_inuvik_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,point_type,comments,geom) 
SELECT gid,1,trend,plunge,point_type,subfeature,ST_MakeValid(geom) FROM sources.nwt_inuvik_points where point_type is not null and geom is not null;
```

**Comment by cambro** [comment]
these data are not on teststrata

**Comment by kaakin** [comment]
Processed during the initial round of candidates processing by Kate. (map_ingestion->sources)
