### ISSUE TITLE
IGS-DWM-173 Bonners Ferry East 30X60

### ISSUE THREAD

**Issue by hsnellen** [UW-Macrostrat/burwell-processing#496]
**Name:**
Bonners Ferry East

**Source URL:**
https://www.idahogeology.org/outgoing/macrostratData/

**Estimated scale:**
Large

**Folder name:**
IGS-DWM-173_BonnersFerryEast30x60_macrostrat.gdb

**Dataset names:**
'dwm173_BonnersFerry_DOMU_xlsx_MacroStratPolyTable' and 'dwm173_BonnersFerry_DOMU_xlsx_DescriptionOfMapUnits'

**Number of bedrock polygons:**
2127

**Lithology field:**
GeneralLithology

**Time field:**
Top, bottom

**Stratigraphy name field:**
strat_name

**Description field:**
Description

**Comments field:**
Comments

**Comments:**
'macroStratFaults', 'GeologicLines', 'Faults', 'ContactsAndFaults', and 'MapUnitPolys'

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
Geologic Map of the East Half of the Bonners Ferry 30 x 60 Minute Quadrangle, Idaho; Breckenridge and others; 2014; https://www.idahogeology.org/product/dwm-173

**Comment by cambro** [comment]
source_id 282
https://dev.macrostrat.org/burwell#10/48.750434999999996/-116.251025
