### ISSUE TITLE
IGS-DWM-43 Twin Falls 30X60

### ISSUE THREAD

**Issue by hsnellen** [UW-Macrostrat/burwell-processing#497]
**Name:**
Twin Falls

**Source URL:**
https://www.idahogeology.org/outgoing/macrostratData/

**Estimated scale:**
Large

**Folder name:**
IGS-DWM-43_TwinFalls30x60_macrostrat.gdb

**Dataset names:**
MacroStratPolyTable

**Number of bedrock polygons:**
1302

**Lithology field:**
GeneralLithology

**Time field:**
'B_age' and 'Top_age'

**Stratigraphy name field:**
strat_name

**Description field:**
Description

**Comments field:**
Comments

**Comments:**
'macroStratFaults', 'GeologicLines', 'Faults', 'ContactsAndFaults', 'MapUnitPolys', and 'MacroStratPolyTable'.

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
Idaho Geological Survey; Geologic Map of the Twin Falls 30 x 60 Minute Quadrangle, Idaho; Othberg and others; 2012; https://www.idahogeology.org/product/gm-49

**Comment by cambro** [comment]
source_id 281
https://dev.macrostrat.org/burwell#10/42.74991/-114.50088
