### ISSUE TITLE
IGS-Dwm-80 Murphy 30X60

### ISSUE THREAD

**Issue by hsnellen** [UW-Macrostrat/burwell-processing#498]
**Name:**
Murphy

**Source URL:**
https://www.idahogeology.org/outgoing/macrostratData/

**Estimated scale:**
Large

**Folder name:**
IGS-DWM-80_Murphy30x60_macrostrat.gdb

**Dataset names:**
'MacroStratPolyTable' and 'DescriptionOfMapUnits'

**Number of bedrock polygons:**
1181

**Lithology field:**
GeneralLit

**Time field:**
'Top_age' and 'B_age'

**Stratigraphy name field:**
strat_name

**Description field:**
Description

**Comments field:**
Comments

**Comments:**
'macroStratFaults', 'GeologicLines', 'Faults', 'ContactsAndFaults', 'MapUnitPolys', 'MacroStratPolyTable', and 'DescriptionOfMapUnits'

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
Idaho Geological Survey; Geologic Map of the Murphy 30 x 60 Quadrangle, Ada, Canyon, Elmore, and Owyhee Counties, Idaho; Bonnichsen and Godchaux; 2006; https://www.idahogeology.org/product/dwm-80

**Comment by cambro** [comment]
This one had a few errors. Some igs_lithology fields were null that should not have been, description was a duplication of name, and stratigraphic hierarchy was included in strat_name field. All fixed prior to import

source_id 280
https://dev.macrostrat.org/burwell#10/43.249885/-116.500955
