### ISSUE TITLE
IGS-DWM-171 Fairfield 30X60

### ISSUE THREAD

**Issue by hsnellen** [UW-Macrostrat/burwell-processing#500]
**Name:**
Fairfield

**Source URL:**
https://www.idahogeology.org/outgoing/macrostratData/

**Estimated scale:**
Large

**Folder name:**
IGS-DWM_171_Fairfield30x60_macrostrat.gdb

**Dataset names:**
macroStratPolyTable

**Number of bedrock polygons:**
3075

**Lithology field:**
GeneralLithology

**Time field:**
'Top_Age' and ' Bottom_Age'

**Stratigraphy name field:**
strat_name

**Description field:**
Descr_

**Comments field:**
Comments

**Comments:**
'Faults', 'GeologicLines', 'macroStratFaults', 'ContactsAndFaults', 'MapUnitPolys', and 'macroStratPolyTable'

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
Idaho Geological Survey; Geologic Map of the Fairfield 30 x 60 Minute Quadrangle, Idaho; Garwood and others; 2014; https://www.idahogeology.org/product/dwm-171

**Comment by cambro** [comment]
source_id 279
https://dev.macrostrat.org/burwell#10/43.249905/-114.50088
