### ISSUE TITLE
IGS-GM-29 Idaho City 30X60

### ISSUE THREAD

**Issue by hsnellen** [UW-Macrostrat/burwell-processing#501]
**Name:**
Idaho City

**Source URL:**
https://www.idahogeology.org/outgoing/macrostratData/

**Estimated scale:**
Large

**Folder name:**
IGS-GM-29_IdahoCity30x60macrostrat.gdb

**Dataset names:**
MacroStratTable

**Number of bedrock polygons:**
3947

**Lithology field:**
GeneralLithology

**Time field:**
'bottom_age' and 'top_age'

**Stratigraphy name field:**
strat_name

**Description field:**
Description

**Comments field:**
Comments

**Comments:**
'macroStratFaults', 'GeologicLines', 'Faults', 'ContactsAndFaults', 'MapUnitPolys', and 'MacroStratTable'

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
Idaho Geological Survey; Geologic map of the Idaho City 30 x 60 Minute quadrangle, Idaho; Kiilsgaard and others; 2001; https://www.idahogeology.org/product/gm-29

**Comment by cambro** [comment]
source_id 278
https://dev.macrostrat.org/burwell#10/43.749894999999995/-115.500925
