### ISSUE TITLE
IGS-GM-45 Deadwood River 30X60

### ISSUE THREAD

**Issue by hsnellen** [UW-Macrostrat/burwell-processing#502]
**Name:**
Deadwood River

**Source URL:**
https://www.idahogeology.org/outgoing/macrostratData/

**Estimated scale:**
Large

**Folder name:**
IGS-GM-45_DeadwoodRiver30x60_macrostrat.gdb

**Dataset names:**
gm45_DeadwoodRiver_DOMU_xlsx_MacroStratPolyTable

**Number of bedrock polygons:**
3778

**Lithology field:**
GeneralLithology

**Time field:**
'Top_age' and 'B_age'

**Stratigraphy name field:**
strat_name

**Description field:**
Description

**Comments field:**
Comments

**Comments:**
'macroStratFaults', 'MapUnitPolys' and 'gm45_DeadwoodRiver_DOMU_xlsx_MacroStratPolyTable'

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by cambro** [comment]
This one was already imported into Macrostrat, source_id 202
https://dev.macrostrat.org/burwell/#10/44.2506/-115.5013
