### ISSUE TITLE
IGS-GM-47 Acro 30X60

### ISSUE THREAD

**Issue by hsnellen** [UW-Macrostrat/burwell-processing#503]
**Name:**
Acro

**Source URL:**
https://www.idahogeology.org/outgoing/macrostratData/

**Estimated scale:**
Large

**Folder name:**
IGS-GM-47_Arco30x60Macrostrat.gdb

**Dataset names:**
MacroStratPolyTable

**Number of bedrock polygons:**
3718

**Lithology field:**
GeneralLithology

**Time field:**
'Bottom_Age' and 'Top_Age'

**Stratigraphy name field:**
strat_name

**Description field:**
Description

**Comments field:**
Comments

**Comments:**
'macroStratFaults', 'GeologicLines', 'Faults', 'ContactsAndFaults', 'MapUnitPolys', and 'MacroStratPolyTable'

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
This one and several others have combined stratigraphic nomenclatural hierarchy into the strat_name field. The strat_name field is for the MOST SPECIFIC name applied. Macrostrat generally already knows hierarchy. This information is useful but should be placed in other field "hierarchy"

**Comment by cambro** [comment]
Idaho Geological Survey; Geologic Map of the Arco 30 x 60 Minute Quadrangle, South-Central Idaho; Skipp and others; 2009; https://www.idahogeology.org/product/gm-47

**Comment by cambro** [comment]
source_id 277
https://dev.macrostrat.org/burwell#10/43.74991/-113.500855
