### ISSUE TITLE
IGS-GM-50 Grangeville 30 X60

### ISSUE THREAD

**Issue by hsnellen** [UW-Macrostrat/burwell-processing#504]
**Name:**
Grangeville

**Source URL:**
https://www.idahogeology.org/outgoing/macrostratData/

**Estimated scale:**
Large

**Folder name:**
IGS-GM-50_Grangeville30x60_macrostrat.gdb

**Dataset names:**
'Glossary', 'macroStratPolyTable', 'DescriptionOfMapUnits', 'DataSources' , 'DataDictionary'.

**Number of bedrock polygons:**
2268

**Lithology field:**
GeneralLithology

**Time field:**
'bottom_age' and 'top_age'

**Stratigraphy name field:**
strat_name

**Description field:**
Description

**Comments field:**
Comments

**Comments:**
'GeologicLines', 'macroStratFaults', 'Faults', 'ContactsAndFaults', 'MapUnitPolys', 'Glossary', 'macroStratPolyTable', 'DescriptionOfMapUnits', 'DataSources' and 'DataDictionary'

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
Idaho Geological Survey; Geologic Map of the Idaho Part of the Grangeville 30 x 60 Minute Quadrangle, and Adjoining Areas of Oregon and Washington; Kauffman and others; 2014; https://www.idahogeology.org/product/gm-50

**Comment by cambro** [comment]
source_id 276
https://dev.macrostrat.org/burwell#10/45.749885/-116.47207499999999
