### ISSUE TITLE
IGS-GM-52 Salmon 30X60

### ISSUE THREAD

**Issue by hsnellen** [UW-Macrostrat/burwell-processing#505]
**Name:**
Salmon

**Source URL:**
https://www.idahogeology.org/outgoing/macrostratData/

**Estimated scale:**
Large

**Folder name:**
IGS-GM-52_Salmon30x60_macrostrat.gdb

**Dataset names:**
gm52domu

**Number of bedrock polygons:**
2471

**Lithology field:**
GeneralLithology

**Time field:**
'Top_age' and 'B_age'

**Stratigraphy name field:**
strat_name

**Description field:**
Description

**Comments field:**
Comments

**Comments:**
'macroStratFaults', 'MapUnitPolys' and 'gm52domu'

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
This looks great! It's not clear what the citation should be or where the link would go to for a user wishing to see (or buy) the original source.

**Comment by cambro** [comment]
Update here: there is a field "comments" that seems to have the right data:
 Idaho Geological Survey; Geologic Map of the Western Part of the Salmon 30 X 60 Minute Quadrangle, Idaho and Montana; Burmester and others ; 2016; https://www.idahogeology.org/product/gm-52

**Comment by cambro** [comment]
source_id 275
https://dev.macrostrat.org/burwell#10/45.24992/-113.688395
