### ISSUE TITLE
Qinnguk, NWT

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#506]
**Name:**
Geology, Qinnguk, Victoria Island, Northwest Territories; Rainbird, R H; Bédard, J H; Thomson, D. Geological Survey of Canada, Canadian Geoscience Map 176, (ed. prelim.), 2014, 1 sheet

**Source URL:**
https://doi.org/10.4095/294837

**Estimated scale:**
large

**Folder name:**
nwt_qinnguk

**Dataset names:**
nwt_qinnguk
nwt_qinnguk_points

**Number of bedrock polygons:**
399

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by rleverett** [comment]
No line files.

Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nwt_qinnguk where geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,strike,dipplunge,azimuth,point_type,strucclass,ST_MakeValid(geom) FROM sources.nwt_qinnguk_points where point_type is not null and geom is not null;
```

**Comment by kaakin** [comment]
Processed during the initial round of candidates processing by Kate. (map_ingestion->sources)
-Only Polygons processed?
