### ISSUE TITLE
Ulukhaktok, NWT

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#507]
**Name:**
Geology, Ulukhaktok, Victoria Island, Northwest Territories; Bédard, J H; Rainbird, R H. Geological Survey of Canada, Canadian Geoscience Map 190, (ed. prelim.), 2015, 1 sheet

**Source URL:**
https://doi.org/10.4095/297279

**Estimated scale:**
large

**Folder name:**
nwt_ulukhaktok

**Dataset names:**
nwt_ulukhaktok
nwt_ulukhaktok_lines
nwt_ulukhaktok_points

**Number of bedrock polygons:**
167

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by rleverett** [comment]
Some unmapped units

Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,descriptio,age,descrip,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nwt_ulukhaktok where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid,1,feature,subfeature,new_type,ST_MakeValid(geom) FROM sources.nwt_ulukhaktok_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,strike,dip,dip_dir,point_type,comments,geom) 
SELECT gid,1,azimuth,dipplunge,dip_dir,point_type,strucclass,ST_MakeValid(geom) FROM sources.nwt_ulukhaktok_points where point_type is not null and geom is not null;
```

**Comment by kaakin** [comment]
Processed during the initial round of candidates processing by Kate. (map_ingestion->sources)
