### ISSUE TITLE
Blayney, NSW

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#517]
**Name:**
Wyborn D. and Henderson G.A.M., 1997, Blayney 1:100 000 Geological Sheet 8730, 1st edition. Geological Survey of New South Wales, Sydney & Geoscience Australia, Canberra

**Source URL:**
https://search.geoscience.nsw.gov.au/product/45

**Estimated scale:**
large

**Folder name:**
nsw_blayney

**Dataset names:**
nsw_blayney
nsw_blayney_lines
nsw_blayney_points

**Number of bedrock polygons:**
738

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
lith_desc

**Comments field:**

**Comments:**

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by rleverett** [comment]
No strike/dip in the points files

Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,unitname,age,lith_desc,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_blayney where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,1,"desc",new_type,ST_MakeValid(geom) FROM sources.nsw_blayney_lines where new_type is not null and geom is not null;
```
```
INSERT INTO points.points (orig_id,source_id,point_type,comments,geom) 
SELECT gid,1,point_type,"desc",ST_MakeValid(geom) FROM sources.nsw_blayney_points where point_type is not null and geom is not null;
```

**Comment by kaakin** [comment]
Processed during the initial round of candidates processing by Kate. (map_ingestion->sources)
