### ISSUE TITLE
Canberra, NSW

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#519]
**Name:**
Abell, R. S.. 1992, Canberra 1:100 000 scale geological map. 8727. 1st Edition, BMR, Canberra
--

**Source URL:**
https://search.geoscience.nsw.gov.au/product/59

**Estimated scale:**
large

**Folder name:**
nsw_canberra

**Dataset names:**
nsw_canberra
nsw_canberra_lines

**Number of bedrock polygons:**
1265

**Lithology field:**
lithology

**Time field:**
use_age

**Stratigraphy name field:**
strat_name

**Description field:**

**Comments field:**

**Comments:**

## Todo:

- [ ] Insert new source record
- [ ] Add data to database
- [ ] Process and add to homogenized tables
- [ ] Process and import lines
- [ ] Process and import points
- [ ] Match
- [ ] Roll tiles

**Comment by rleverett** [comment]
No points files

Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,1,unit_name,use_age,lithology,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_canberra where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid,1,feature,descript,new_type,ST_MakeValid(geom) FROM sources.nsw_canberra_lines where new_type is not null and geom is not null;
```

**Comment by kaakin** [comment]
Processed during the initial round of candidates processing by Kate. (map_ingestion->sources)
