### ISSUE TITLE
Cobar, NSW

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#520]
**Name:**
Glen R.A., 1994, Cobar 1:100 000 Geological Sheet 8035, 2nd edition. Geological Survey of New South Wales, Sydney
--

**Source URL:**
https://search.geoscience.nsw.gov.au/product/70

**Estimated scale:**
large

**Folder name:**
nsw_cobar

**Dataset names:**
nsw_cobar
nsw_cobar_lines

**Number of bedrock polygons:**
2963

**Lithology field:**

**Time field:**
age

**Stratigraphy name field:**
strat_name

**Description field:**
descriptio

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by rleverett** [comment]
No point files

Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,strat_name,t_interval,b_interval,geom) 
SELECT gid,286,formation,age,descriptio,strat_name,late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_cobar where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,new_type,geom) 
SELECT gid,286,descriptio,new_type,ST_MakeValid(geom) FROM sources.nsw_cobar_lines where new_type is not null and geom is not null;
```

**Comment by cambro** [comment]
lots of errors on this one, but fixed prior to insert.
source_id 286
https://dev.macrostrat.org/burwell#10/-31.241585/145.73980999999998
