### ISSUE TITLE
Cobbora, NSW

### ISSUE THREAD

**Issue by rleverett** [UW-Macrostrat/burwell-processing#521]
**Name:**
Meakin N.S., Henderson G.A.M., Podgon D.J., Colqhoun G.P. and Barron L., 2000, Cobbora 1:100 000 Geological Sheet 8733, 1st edition. Geological Survey of New South Wales, Sydney & Geoscience Australia, Canberra
--

**Source URL:**
https://search.geoscience.nsw.gov.au/product/71

**Estimated scale:**
large

**Folder name:**
nsw_cobbora

**Dataset names:**
nsw_cobbora
nsw_cobbora_lines
nsw_cobbora_points

**Number of bedrock polygons:**
1672

**Lithology field:**

**Time field:**
age_

**Stratigraphy name field:**
strat_name

**Description field:**
descrip

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [ ] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by rleverett** [comment]
No strike/dip information in the points files.

Suggested Inserts:
```
INSERT INTO maps.large (orig_id,source_id,name,age,descrip,comments,strat_name,t_interval,b_interval,geom) 
SELECT gid,283,unitname,age_,trim(descrip),trim(maingroup),trim(strat_name),late_id,early_id,ST_MakeValid(geom) FROM sources.nsw_cobbora where geom is not null;
```
```
INSERT INTO lines.large (orig_id,source_id,descrip,name,new_type,geom) 
SELECT gid, 283,descriptio,feat_name,new_type,ST_MakeValid(geom) FROM sources.nsw_cobbora_lines where new_type is not null and geom is not null;
```

**Comment by cambro** [comment]
errors in strat_name field: 
```
update sources.nsw_cobbora set strat_name=NULL where strat_name like 'UNGROUPED%';
update sources.nsw_cobbora set strat_name=NULL where strat_name like 'Undifferentiated';
update sources.nsw_cobbora set strat_name=NULL where strat_name like 'SURAT BASIN (of the GREAT AUSTRALIAN BASIN)';
update sources.nsw_cobbora set strat_name=NULL where strat_name like 'ORDOVICIAN INTRUSION';
update sources.nsw_cobbora set strat_name=NULL where strat_name like 'MESOZOIC IGNEOUS ROCKS';
update sources.nsw_cobbora set strat_name=NULL where strat_name like 'GUNNEDAH BASIN';
update sources.nsw_cobbora set strat_name=NULL where strat_name like 'DEVONIAN INTRUSIONS';
update sources.nsw_cobbora set strat_name=NULL where strat_name like 'Cainozoic undifferentiated';
update sources.nsw_cobbora set strat_name=NULL where strat_name like 'CAINOZOIC UNITS';
```
source_id 283
https://dev.macrostrat.org/burwell#10/-32.24843/149.25117
