### ISSUE TITLE
IGS-DWM-189 Sandpoint 30x60

### ISSUE THREAD

**Issue by hsnellen** [UW-Macrostrat/burwell-processing#559]
**Name:**
IGS-DWM-189 Sandpoint 30x60

**Source URL:**
https://www.idahogeology.org/outgoing/macrostratData/newFile/IGS-DWM-189_Sandpoint30x60_macrostrat.gdb.zip

**Estimated scale:**
Large

**Folder name:**

**Dataset names:**

**Number of bedrock polygons:**
3,473

**Lithology field:**
None

**Time field:**
DescriptionOfMapUnits

**Stratigraphy name field:**
DescriptionOfMapUnits

**Description field:**
DescriptionOfMapUnits

**Comments field:**

**Comments:**

## Todo:

- [x] Insert new source record
- [x] Add data to database
- [x] Process and add to homogenized tables
- [x] Process and import lines
- [x] Process and import points
- [x] Match
- [x] Roll tiles

**Comment by cambro** [comment]
A few minor modifications required, mostly involving lithology field and removing genetic/other information to comments.

source_id 292.
https://dev.macrostrat.org/burwell#10/48.24992/-116.521585
